name: music_rec
channels:
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aom=3.12.1=h00a0c3c_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py39hc99e966_0
  - brotlicffi=1.0.9.2=py39h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.10.5=py39haa95532_0
  - cffi=2.0.0=py39h02ab6af_0
  - charset-normalizer=3.4.4=py39haa95532_0
  - contourpy=1.2.1=py39h214f63a_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - eigen=5.0.1=h3ba6905_0
  - expat=2.7.3=h885b0b7_4
  - ffmpeg=6.1.1=haa678a1_5
  - filelock=3.17.0=py39haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py39h02ab6af_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - gflags=2.2.2=hd77b12b_1
  - giflib=5.2.2=h7edc060_0
  - glog=0.5.0=hd77b12b_1
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py39h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - gst-plugins-base=1.24.12=h91a6125_1
  - gstreamer=1.24.12=hfb93a4f_1
  - gstreamer-orc=0.4.41=ha00e802_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py39haa95532_0
  - importlib_resources=6.5.2=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py39haa95532_0
  - jpeg=9f=ha349fce_0
  - kiwisolver=1.4.4=py39hd77b12b_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.3.0=h5bd13ec_0
  - libclang13=20.1.8=default_hccbf073_0
  - libdeflate=1.22=h5bf469e_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.16=h2bbff1b_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libkrb5=1.21.3=h885b0b7_4
  - libllvm20=20.1.8=h3aa9ab2_0
  - libogg=1.3.5=h2bbff1b_1
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libtheora=1.2.0=habf309d_1
  - libtiff=4.7.1=h3a18249_0
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.6.0=h55ef9bb_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py39h827c3e9_0
  - matplotlib=3.9.2=py39haa95532_1
  - matplotlib-base=3.9.2=py39he19b0ae_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h827c3e9_2
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py39haa95532_0
  - mysql-common=9.3.0=hc394544_4
  - mysql-libs=9.3.0=h58c8544_4
  - networkx=3.2.1=py39haa95532_0
  - numexpr=2.10.1=py39h4cd664f_0
  - numpy=2.0.2=py39h055cbcc_0
  - numpy-base=2.0.2=py39h65a83cf_0
  - opencv=4.12.0=py39h6fcf9f4_0
  - openjpeg=2.5.4=h56d5a42_1
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py39haa95532_1
  - pandas=2.3.3=py39ha5e6156_0
  - pcre2=10.46=h5740b90_0
  - pillow=11.3.0=py39hb328d1f_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - ply=3.11=py39haa95532_0
  - pycparser=2.23=py39haa95532_0
  - pyparsing=3.2.0=py39haa95532_0
  - pyqt=5.15.10=py39h5da7b33_1
  - pyqt5-sip=12.13.0=py39h827c3e9_1
  - pysocks=1.7.1=py39haa95532_1
  - python=3.9.25=h716150d_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytorch=2.5.1=py3.9_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=py39haa95532_0
  - pyyaml=6.0.2=py39h827c3e9_0
  - qt-main=5.15.2=h8b2cd8b_13
  - qtbase=6.9.2=hd965823_2
  - requests=2.32.5=py39haa95532_0
  - setuptools=72.1.0=py39haa95532_0
  - sip=6.7.12=py39h5da7b33_1
  - six=1.17.0=py39haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - sympy=1.14.0=py39haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py39haa95532_0
  - torchvision=0.20.1=py39_cpu
  - tornado=6.5.1=py39h827c3e9_0
  - typing_extensions=4.15.0=py39haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py39haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zipp=3.21.0=py39haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0

